### ISSUE TITLE
Wrong result if program reads no input.

### ISSUE THREAD

**Issue by Krigpl** [dj3500/hightail#42]
If tested program reads no input (but the testcase has input), it can termiante before we write the input to the stdin and it will cause IOStreamException Broken Pipe or Stream Closed. Then the result will be "aborted" while it should process the testcase normally comparing output with expected output.

**Comment by ASTGS** [comment]
When is such a scenario expected to arise?

**Comment by dj3500** [comment]
Not too often, for sure. Although it did come up for Krig as you can see :)

**Comment by ASTGS** [comment]
OK. I tried a couple of problems from codeforces to get the situation (mentioned above).
But in all the cases hightail seems to be working fine.
Please correct me if my understanding of the issue is incorrect:
If we have a problem which takes no input, and in hightail we have specified some input, then since the program will terminate before anything would be written to stdin, and hence IOStreamException is expected to be thrown. Right?
@Krigpl Can you please share a link to the problem, while testing which you encountered this exception?
PFA the screenshot: 
![hightail_bug_1](https://cloud.githubusercontent.com/assets/9794969/8898626/f8c6bfbc-3444-11e5-9c60-9f0d3b179e54.jpg)

**Comment by Krigpl** [comment]
It was quite a long time ago and I don't recall any details. But if it
seems to be working now I would assume the bug is gone.

2015-07-26 21:21 GMT-07:00 ASTGS <notifications@github.com>:
